### ISSUE TITLE
Error while redistribute the Epetra.MultiVector my_nodes

### ISSUE THREAD

**Issue by xander9595** [johntfoster/PDpy#2]
Hi, I am facing issues while running PD.py.
Form the message below, it seems like some error happens when redistribute the Epetra.MultiVector my_nodes.
I also tring to run some easy redistribute example by Pytrilinos 12.18.1, like Vector , CrsMatrix. It all works. However, when I was tring to redistribute the MultiVector, I got the same error as running PD.py.
So, how can I fix this bug?@johntfoster 

Here is the error message:

:mpiexec -np 2 python PD.py

PD.py version 0.4.0

Inserting precracks...

Load balancing...

Traceback (most recent call last):
  File "PD.py", line 349, in <module>
Traceback (most recent call last):
  File "PD.py", line 349, in <module>
    my_nodes_balanced = redistributer.redistribute(my_nodes)
    my_nodes_balanced = redistributer.redistribute(my_nodes)
  File "/home/diehl/anaconda2/lib/python2.7/site-packages/PyTrilinos/Isorropia/Epetra.py", line 606, in redistribute
  File "/home/diehl/anaconda2/lib/python2.7/site-packages/PyTrilinos/Isorropia/Epetra.py", line 606, in redistribute
    return _Epetra.Redistributor_redistribute(self, *args)
ValueError: 'dist_type' value 'n' is unrecognized
    return _Epetra.Redistributor_redistribute(self, *args)
ValueError: 'dist_type' value 'n' is unrecognized

**Comment by lbh-zmm** [comment]
349       my_nodes_balanced = redistributer.redistribute(my_nodes)
I installed everything through CONDA, but the program exited on line 349
